language: python
python:
    - 2.7
install:
    - pip install -r test_requirements.txt
before_script:
    - cp travis_settings local_settings.py
script:
    - nosetests --with-coverage
    - coverage xml
    - diff-cover coverage.xml
    - bandit -x tests -r .
