language: python
python:
    - 2.7
install:
    - pip install -r test_requirements.txt
before_script:
    - cp travis_settings local_settings.py
script:
    - nosetests --with-coverage --cover-package=. --cover-erase --cover-min-percentage=75
    - bandit -x tests -r .
