version: '3.4'

services:
    mediawaiter:
        image: kyokley/mediawaiter
        environment:
          - FLASK_APP=waiter
          - FLASK_DEBUG=1
        build:
            context: .
            target: dev
        command:
            sh -c "python waiter.py"
        hostname: mediawaiter
        ports:
          - "127.0.0.1:5000:5000"
        tty: true
        stdin_open: true
        networks:
          - mediawaiter-backend
        volumes:
          - ./:/code
          - ./static/assets:/var/static/assets
          - ./configs/docker_settings.py:/code/local_settings.py

# Persistent Volumes
volumes:
  mediawaiter-data:

networks:
    mediawaiter-backend:
