version: '2'

services:
    mediawaiter:
        image: kyokley/mediawaiter
        environment:
          - FLASK_APP=waiter
          - FLASK_DEBUG=1
        build:
            context: .
            target: dev
        command:
            sh -c "cp configs/docker_settings.py local_settings.py && python waiter.py"
        hostname: mediawaiter
        ports:
          - "5000:5000"
        tty: true
        stdin_open: true
        networks:
          - mediawaiter-backend
        volumes:
          - ./:/code

# Persistent Volumes
volumes:
  mediawaiter-data:

networks:
    mediawaiter-backend:
