services:
  mediawaiter:
    image: kyokley/mediawaiter
    environment:
      - FLASK_APP=src.mediawaiter.waiter
      - FLASK_DEBUG=1
      - MW_USE_NGINX=false
      - MW_HOST=0.0.0.0
      - MW_BASE_PATH=/www/media
      - MW_LOG_DIR=/logs
      - MW_MEDIAWAITER_PROTOCOL=http://
      - MW_IGNORE_MEDIA_DIR_CHECKS=true
    build:
      context: .
      target: dev
    command: sh -c "python -m src.mediawaiter.waiter"
    hostname: mediawaiter
    ports:
      - "127.0.0.1:5000:5000"
    tty: true
    stdin_open: true
    networks:
      - mediawaiter-backend
    volumes:
      - ./:/code
      - ./static/assets:/var/static/assets
# Persistent Volumes
volumes:
  mediawaiter-data:
networks:
  mediawaiter-backend:
