version: '2'

services:
    mediawaiter:
        image: kyokley/mediawaiter
        build: .
        command:
            sh -c "python waiter.py"
        hostname: mediawaiter
        ports:
          - "5000:5000"
        tty: true
        stdin_open: true
        networks:
          - mediawaiter-backend
        volumes:
          - ./:/code

# Persistent Volumes
volumes:
  mediawaiter-data:

networks:
    mediawaiter-backend:
